export const comments: readonly { comment: string }[] = [
  { comment: "Amazing product! Highly recommend it." },
  { comment: "Not bad, but could be improved." },
  { comment: "Exceeded my expectations!" },
  { comment: "Arrived quickly and well-packaged." },
  { comment: "Worth every penny!" },
  { comment: "The quality could be better for the price." },
  { comment: "Absolutely love it! Will buy again." },
  { comment: "Decent product, but delivery took too long." },
  { comment: "Great product for the price." },
  { comment: "Wouldn't recommend. Didn't meet expectations." },
  { comment: "This is my second purchase, and I'm still happy with it!" },
  { comment: "It works fine, but nothing extraordinary." },
  { comment: "Perfect for my needs. Very satisfied." },
  { comment: "Good value for money!" },
  { comment: "It was just okay. Not sure I'd buy again." },
  { comment: "Superb quality and design!" },
  { comment: "Product is fine, but I found it cheaper elsewhere." },
  { comment: "It looks great and functions perfectly." },
  { comment: "Not what I expected, but still decent." },
  { comment: "Five stars! Exceeded all expectations." },
];
